
trigger:
- azure-pipelines

pool: personal

steps:

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure for Students(3dfa5484-e471-4491-80c3-dd5aec29ab6b)'
    azureContainerRegistry: '{"loginServer":"registrylearndata.azurecr.io", "id" : "/subscriptions/3dfa5484-e471-4491-80c3-dd5aec29ab6b/resourceGroups/LearnData/providers/Microsoft.ContainerRegistry/registries/RegistryLearnData"}'
    dockerComposeFile: 'docker-compose-jenkins.yml'
    action: 'Run a Docker Compose command'