# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool: personal

jobs:
- job: A
  steps:
  - script: echo Inicio!
    displayName: 'Inicion pepiline'
- job: B
  steps:
    - script: echo "Segundo job"
      displayName: 'segundo job'
